[telegram]
token = "6838155431:AAEdPdx6WMTS1pJq7PEV5RHqb_Sgo_NAM3E"
workers = 1
admins = [1234567]
admins_only = false
maintenance_mode = false
persistent_temp_data = true

[pyrogram]
enabled = false
api_id = 0
api_hash = ""

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = ""
issues = ""
channel = ""
